set -g default-terminal "tmux-256color"
set -g prefix C-s                    # remap leader to Ctrl-s
set -g history-limit 100000          # scrollback history
set -g cursor-style block            # cursor style
set -ga terminal-overrides "*:RGB"   # terminal color support

# style
thm_red="#DA4543"
thm_green="#80E091"
thm_blue="#659FF8"

set -g status-position top
set -g status-style "fg=default,bg=default"
set -g status-left "#[fg=${thm_green},bold]   #S#[fg=default,nobold] |"
set -g status-right "#[fg=${thm_green},bold] 󰃰 %I:%M %p, %d-%b-%y, %a "
set -g status-left-length 100
set -g status-right-length 100
set -g window-status-current-format "#[fg=${thm_red},bold] #[underscore] #I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${thm_green},bg=default"
set -g mode-style "fg=${thm_green},bg=default"
set -g pane-border-style "fg=default"
set -g pane-active-border-style "fg=${thm_blue}"
