set -g default-terminal "tmux-256color"
set -g prefix C-s                    # remap leader to Ctrl-s
set -g history-limit 100000          # scrollback history
set -g cursor-style block            # cursor style
set -ga terminal-overrides "*:RGB"   # terminal color support

# color palette
thm_bg="#222436"
thm_fg="#c8d3f5"
thm_cyan="#86e1fc"
thm_black="#1b1d2b"
thm_gray="#3a3f5a"
thm_magenta="#c099ff"
thm_pink="#ff757f"
thm_red="#ff757f"
thm_green="#c3e88d"
thm_yellow="#ffc777"
thm_blue="#82aaff"
thm_orange="#ff9e64"
thm_black4="#444a73"

# style
set -g status-position top
set -g status-style "fg=${thm_fg},bg=default"
set -g status-left "#[fg=${thm_green},bold]   #S#[fg=${thm_green},nobold] |"
set -g status-right "#[fg=${thm_green},bold] 󰃰 %I:%M %p, %d-%b-%y, %a "
set -g status-left-length 100
set -g status-right-length 100
set -g window-status-current-format "#[fg=${thm_green},bold]  #I:#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${thm_green},bg=default"
set -g mode-style "fg=${thm_green},bg=default"
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_green}"
set -g pane-border-style "fg=${thm_gray}"
