set -g default-terminal "tmux-256color"
set -g prefix C-s                    # remap leader to Ctrl-s
set -g history-limit 10000           # scrollback history
set -g cursor-style block            # cursor style
set -ga terminal-overrides "*:RGB"   # terminal color support

# status bar layout
set -g status-right "%I:%M %p, %d-%b-%y, %a"
set -g status-left-length 20

